USE [master]
GO

/****** Object:  Database [ECommerceYT]    Script Date: 17/4/2025 12:53:07 AM ******/
CREATE DATABASE [ECommerceYT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ECommerceYT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ECommerceYT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ECommerceYT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ECommerceYT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECommerceYT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECommerceYT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECommerceYT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECommerceYT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECommerceYT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECommerceYT] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECommerceYT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECommerceYT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECommerceYT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECommerceYT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECommerceYT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECommerceYT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECommerceYT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECommerceYT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECommerceYT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECommerceYT] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ECommerceYT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECommerceYT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECommerceYT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECommerceYT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECommerceYT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECommerceYT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECommerceYT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECommerceYT] SET RECOVERY FULL 
GO

ALTER DATABASE [ECommerceYT] SET  MULTI_USER 
GO

ALTER DATABASE [ECommerceYT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECommerceYT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ECommerceYT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ECommerceYT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ECommerceYT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ECommerceYT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ECommerceYT] SET QUERY_STORE = ON
GO

ALTER DATABASE [ECommerceYT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ECommerceYT] SET  READ_WRITE 
GO

